server:
  port: ${SERVER_PORT:9991}
spring:
  data:
    mongodb:
      host: mongodb://${DB_USERNAME:root}:${DB_PASSWORD:password}@${DB_HOST:localhost}/${DB_NAME:doc-prod}?authSource=admin&authMechanism=MONGODB-CR
      database: ${DB_NAME:doc-prod}
      port: ${DB_PORT:27017}